project:
  type: website
  output-dir: docs

website:
  title: "SpatialSimBench"
  description: "Spatial Benchmark"
  navbar: 
    left: 
      - href: index.qmd
        text: About
      - href: results/index.qmd
        text: Results

format:
  html:
    page-layout: full
    css: styles.css
    toc: true


editor: visual

page-footer:
  center: "#&copy Sydney Precision Data Science Center"